fruits=["apple","banana","mango"]
print(fruits[0])
print(fruits[2])
print(fruits[-2])
fruits=["apple","banana","mango"]
print(len(fruits))
fruits=["apple","banana"]
fruits.append("mango")
print(fruits)
fruits.insert(1,"orange")
print(fruits)
fruits.remove("apple")
print(fruits)
numbers=[1,2,3]
numbers.pop(1)
print(numbers)
numbers=[30,10,20]
numbers.sort()
print(numbers)
fruits=["apple","banana","mango"]
fruits.sort()
print(fruits)
letters=["A",'B','C','D']
letters.sort()
print(letters)
numbers=[10,20,30]
numbers.reverse()
print(numbers)