chocolate=40
biscuit=40
total=chocolate+biscuit
print(total)
balance=4000
withdraw=2000
remaining=balance-withdraw
print(remaining)
salary=40000
days=24
monthly=salary*days
print(monthly)
dosha=40
idly=2
sharing=dosha//idly
print(sharing)
roomrent=4000
roomates=2
sharing=roomrent//roomates
print(sharing)
x=10,40
print(x)
print(type(x))
dosa_price=40
sharing=2
price_per_person=dosa_price//sharing
print(price_per_person)
roomrent=6000
room_sharing=2
rent_per_person=roomrent/room_sharing
print(rent_per_person)
samosa=10
friends=3
remainder=samosa%friends
print(remainder)
print(15%4)
side=12
area=side **4
print(area)


