name="Akshaya"
print(name)
print(type(name))
name="python"
print(name[0])
name="python"
print(name[-1])
name="python"
print(name[-4])
name="hyderabad"
print(name[-3])
course="SQL"
print(course[-2])
word="programming"
print(word[0])
print(word[-1])
name="python"
print(name[0:2])
name="python"
print(name[1:5])
city="hyderabad"
print(city[2:6])
course="programming"
print(course[:4])
word="developer"
print(word[5:])